[build-system]
requires = [
	"setuptools>=50.0",
	"setuptools_scm[toml]>=6.0",
	"setuptools_scm_git_archive",
	"wheel>=0.33",
	"numpy>=1.16",
	"cython>=0.29",
	]

[tool.setuptools_scm]
write_to = "gpax/_version.py"

[tool.black]
line-length = 120

[tool.pytest.ini_options]
python_files = ["test_*.py"]
python_functions = ["test_*"]